### ISSUE TITLE
Outgoing memo not being shown in list command

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/lightwalletclient#5]
Sent a transaction with a memo. However, `list` shows the memo as null whereas it is included in the tx as indicated by ZecWallet.

<img width="625" alt="CleanShot 2019-09-18 at 14 06 12@2x" src="https://user-images.githubusercontent.com/135382/65185966-7b5b5280-da1d-11e9-999d-8267528b3bce.png">

<img width="1160" alt="CleanShot 2019-09-18 at 14 05 39@2x" src="https://user-images.githubusercontent.com/135382/65185940-6bdc0980-da1d-11e9-92d4-24b7b849315f.png">

**Comment by adityapk00** [comment]
Outgoing metadata is now stored 3479dc345a69dcf30af543dc76725c6bac550bc7
