### ISSUE TITLE
Missing params

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/lightwalletclient#6]
```
./zeclite-cli
Creating Light Wallet
Failed to start wallet. Error was:
Couldn't read /root/.zcash-params/sapling-output.params
```

Tried this on a fresh machine and fails due to missing params. Perhaps it can download the params if missing as running the current fetch-params will result in unneeded Sprout params also?

**Comment by garethtdavies** [comment]
I should have noted I built this from source

**Comment by adityapk00** [comment]
Params are now embedded in the binary. https://github.com/adityapk00/lightwalletclient/commit/48bf5f3f63d5be99ad59d54566a1a9fe0956d9d7
